[package]
name = "models"
edition = "2024"

[dependencies]
constants = { path = "../constants" }
time = { version = "0.3", features = ["serde", "macros", "formatting"] }
serde = { version = "1.0", features = ["derive"] }
