[package]
name = "cli"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "ofcli"
path = "src/main.rs"

[dependencies]
df-sdk = { path = "../df-sdk" }
tokio = { version = "1.48", features = ["macros", "rt-multi-thread"] }
tokio-stream = { version = "0.1", default-features = false }
